### ISSUE TITLE
Doesn't automatically load the values.

### ISSUE THREAD

**Issue by GMPranav** [hawkerm/LiveSplit.ASLVarViewer#6]
When I close LiveSplit and open it again, I have to manually set each value for to work. I dont have to change anything but I have to just click on each of the layout tile in the layout edit window to "activate it". Also, I can confirm that its possible to select the variables only when state is loaded as mentioned in #5 , I hoped this would be a one time setup so I didn't bother about it seems like its not.

I must also mention that I am using a later version of LiveSplit (1.8.16), maybe it works with the earlier version mentioned here but it would be nice to have support for the latest version nonetheless :)

**Comment by GMPranav** [comment]
Update: I just tested 1.6.8, still having the same issue. This is both good and bad because, seems like there is nothing extra to be done for the script to make it work for 1.8.16 (as the behavior is exact same), but I don't get even a temporary solution.

**Comment by hawkerm** [comment]
Thanks for the report @GMPranav. I haven't done much with LiveSplit in a long time unfortunately. If you have any suggestions or find a solution, feel free to open a PR.

**Comment by GMPranav** [comment]
Thats fair, I am nowhere near knowledgeable about this kind of coding. I found an alternative solution for my need, apparently its possible to display it directly by coding in the ASL nowadays. Thanks for taking your time to respond!
